version: '3'
services:
    web:
        image: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./html:/var/www/html
        depends_on:
            - php
            - db

    php:
        build:
            context: .docker
            args:
                WWWUSER: 'laravel'
                WWWUID: '1000'
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./html:/var/www/html

    composer:
        image: composer
        volumes:
            - ./html:/app
        command: install

    db:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./.docker/conf/mysql/:/docker-entrypoint-initdb.d/
            - ./.docker/database/:/var/lib/mysql
        environment:
           - MYSQL_ROOT_PASSWORD=changerootpassword
           - MYSQL_DATABASE=${DB_DATABASE}
           - MYSQL_USER=${DB_USERNAME}
           - MYSQL_PASSWORD=${DB_PASSWORD}

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    # Добавляем новую службу для сборки фронтенда (Node.js)
    # frontend:
    #     image: node:lts
    #     working_dir: /usr/src/app
    #     volumes:
    #         - ./html:/usr/src/app
    #     command: bash -c "npm install && npm run dev" # или yarn install && yarn dev
    #     ports:
    #         - 3000:3000 # порт разработки фронтенда
    #     depends_on:
    #         - php
